name: check nexus





on:
  push:
    branches:
      - main
      - 'feature-branch'
  workflow_dispatch:


jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: login to nexus repository onec2
        uses: docker/login-action@v3
        with:
          registry: http://${{ secrets.NEXUS_URL }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Build Docker image for nexus
        run: |
          docker build -t ${{ secrets.NEXUS_URL}}/my-app:latest .

      - name: Push Docker image to Nexus
        run: |
          docker push ${{ secrets.NEXUS_HOST }}/my-app:latest

      - name: docker build
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
            ${{ github.repository_owner }}/solar-system:${{ github.sha }}
          
      - name: docker push to dockerhub
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

      - name: docker push to ghcr
        continue-on-error: true
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha }}
  dev-deploy:
    needs: [docker]
    runs-on: [self-hosted, macOS, X64, feature]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.26.0'
      - uses: azure/k8s-set-context@v4
        with:
           method: kubeconfig
           kubeconfig: ${{ secrets.KUBE_CONFIG }} 
      - name: checking if k8s works
        run: |
          echo '-------------'
          kubectl get pods
          echo '-------------'
          kubectl get nodes
