name: hacking-purposes
on:
  workflow_dispatch:
  issues:
    types:
      - opened
      - closed
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checking
        env:
          AWS_SECRET_KEY: "siema"
        run: |
          issue_title="${{ github.issue.title }}"
          if [[ "${issue_title}" == *"bug"* ]]; then
            echo "ABCD"
          else
            echo "EFG"
          fi
