name: hacking-purposes
on:
	issues:
		types:
		- opened
jobs:
	test:
		runs-on: ubuntu-latest
		steps:
			- name:
			  env:
				  AWS_SECRET_KEY: "siema"
			  run: |
				issue_title="${{ github.issue.title }}"
				if [[ "${issue_title}" == *"bug"* ]]; then
					echo "ABCD"
				else
					echo "EFG"
				fi
