name: secret-demo
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: hehe
        run: echo ${{ secrets.dev_api_key }}
      - name: hoho
        run: echo ${{ secrets.dev_api_key }} | sed 's/./& /g'
