name: Solar System Workflow



on:
  push:
    branches:
      - main
      - 'feature-branch'
  workflow_dispatch:

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
  unit-testing:
    runs-on: ${{ matrix.operating_system }} 
    strategy:
      matrix:
        node_version: [18]
        operating_system: [ubuntu-latest, macos-latest]
        exclude:
          - node_version: 18
            operating_system: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install npm
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_versions }}
      - name: Install dependencies
        run: npm install

      - name: Unit tests
        run: npm test
      - name: Archiving test report
        uses: actions/upload-artifact@v4
        with:
          name: my-artifacts-${{ strategy.job-index }}
          path: test-results.xml
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install npm
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_versions }}
      - name: Install dependencies
        run: npm install

      - name: Unit tests
        run: npm run coverage
        continue-on-error: true
      - name: Archiving test report
        uses: actions/upload-artifact@v4
        with:
          name: my-test-coverage-${{ strategy.job-index }}
          path: test-results.xml
